const $=s=>document.querySelector(s);let imageData=null,lastResult=null;
const file=$('#file'),drop=$('#drop'),analyze=$('#analyze'),source=$('#source'),overlay=$('#overlay');
fetch('/api/health').then(r=>r.json()).then(x=>{$('#health').textContent='READY';$('#device').textContent=(x.device+' · '+x.model_supervision).toUpperCase().replaceAll('_',' ');}).catch(()=>{$('#health').textContent='OFFLINE';});
function loadFile(f){if(!f)return;const reader=new FileReader();reader.onload=()=>{imageData=reader.result;source.src=imageData;source.hidden=false;overlay.hidden=true;$('.empty').hidden=true;$('#viewerTools').hidden=false;analyze.disabled=false;};reader.readAsDataURL(f)}
file.onchange=e=>loadFile(e.target.files[0]);['dragenter','dragover'].forEach(n=>drop.addEventListener(n,e=>{e.preventDefault();drop.classList.add('drag')}));['dragleave','drop'].forEach(n=>drop.addEventListener(n,e=>{e.preventDefault();drop.classList.remove('drag')}));drop.addEventListener('drop',e=>loadFile(e.dataTransfer.files[0]));
function syncMode(){const cartilage=$('#mode').value==='cartilage';$('#stainField').hidden=!cartilage;$('#legend').hidden=!cartilage;document.querySelector('[data-mode="overlay"]').hidden=!cartilage;if(!cartilage){overlay.hidden=true;source.hidden=!imageData}}
$('#mode').onchange=syncMode;syncMode();
analyze.onclick=async()=>{analyze.disabled=true;$('#progress').hidden=false;$('#warnings').textContent='Analysis running locally...';try{const response=await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image_data:imageData,mode:$('#mode').value,stain:$('#stain').value,pixel_size_um:Number($('#scale').value)})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Analysis failed');lastResult=data;render(data)}catch(error){$('#warnings').innerHTML=`<div class="alert">${escapeHtml(error.message)}</div>`}finally{$('#progress').hidden=true;analyze.disabled=false}};
function number(v,d=3){return v===null||v===undefined?'--':Number(v).toFixed(d)}
function render(data){const m=data.metrics,isCartilage=data.analysis_mode==='cartilage';overlay.src=data.overlay_png;overlay.hidden=!isCartilage;source.hidden=false;$('#orientation').textContent=number(m.orientation_degrees,1)+'°';$('#anisotropy').textContent=number(m.anisotropy);$('#entropy').textContent=number(m.angular_entropy);$('#frequency').textContent=number(m.characteristic_frequency_cycles_per_mm,1);$('#spectrum').src=data.spectrum_png;$('#spectrum').hidden=false;$('#tileCount').textContent=`${m.analyzed_tiles} ${isCartilage?'ROI':'field'} tiles · ${data.elapsed_seconds}s`;$('#warnings').innerHTML=data.warnings.map((w,i)=>`<div class="${i===data.warnings.length-1?'alert':''}">${escapeHtml(w)}</div>`).join('');$('#export').disabled=false}
document.querySelectorAll('.mode').forEach(b=>b.onclick=()=>{document.querySelectorAll('.mode').forEach(x=>x.classList.toggle('active',x===b));const show=b.dataset.mode==='overlay';overlay.hidden=!show;source.hidden=false});$('#opacity').oninput=e=>overlay.style.opacity=Number(e.target.value)/100;
$('#export').onclick=()=>{if(!lastResult)return;const clean={...lastResult};delete clean.overlay_png;delete clean.mask_png;delete clean.spectrum_png;const blob=new Blob([JSON.stringify(clean,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`nostos_${Date.now()}.json`;a.click();URL.revokeObjectURL(a.href)};
function escapeHtml(s){const d=document.createElement('div');d.textContent=s;return d.innerHTML}
