from __future__ import annotations

import argparse
import json
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import torch

from nostos.segmentation.osteochondral import OsteochondralUNet, SliceRecord, load_pair, postprocess_probability
from nostos.validation.osteochondral_interface import reference_interface


def main() -> None:
    parser = argparse.ArgumentParser(description="Render worst-group learned-adapter overlays")
    parser.add_argument("--receipt", type=Path, required=True)
    parser.add_argument("--checkpoints", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--groups", type=int, default=8)
    args = parser.parse_args()
    payload = json.loads(args.receipt.read_text(encoding="utf-8"))
    rows = payload["slice_results"]
    grouped: dict[tuple[str, str, str], list[dict]] = {}
    for row in rows:
        grouped.setdefault((row["patient"], row["sample"], row["family"]), []).append(row)
    ranked = sorted(grouped.items(), key=lambda item: np.median([r["median_absolute_error_um"] for r in item[1]]), reverse=True)
    selected = []
    for key, group in ranked[: args.groups]:
        median = float(np.median([r["median_absolute_error_um"] for r in group]))
        row = min(group, key=lambda value: abs(value["median_absolute_error_um"] - median))
        selected.append((key, row, median))

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    models: dict[int, OsteochondralUNet] = {}
    fig, axes = plt.subplots(2, (len(selected) + 1) // 2, figsize=(14, 7), constrained_layout=True)
    for axis, (key, row, group_median) in zip(axes.ravel(), selected, strict=False):
        fold = int(row["fold"])
        if fold not in models:
            model = OsteochondralUNet().to(device)
            saved = torch.load(args.checkpoints / f"fold_{fold}.pt", map_location=device, weights_only=True)
            model.load_state_dict(saved["state_dict"]); model.eval(); models[fold] = model
        sample_root = Path(row["image_path"]).parents[1] if "image_path" in row else None
        if sample_root is None:
            raise SystemExit("Receipt lacks image_path; pass a receipt generated by the diagnostic-capable runner.")
        record = SliceRecord(row["patient"], row["sample"], row["family"], row["index"],
                             Path(row["image_path"]), Path(row["mask_path"]))
        image, mask = load_pair(record)
        with torch.inference_mode():
            probability = torch.sigmoid(models[fold](image[None].to(device))).cpu().numpy()[0, 0]
        predicted = reference_interface(postprocess_probability(probability))
        truth = reference_interface(mask.numpy()[0] > 0.5)
        axis.imshow(image.numpy()[0], cmap="gray", vmin=0, vmax=1)
        columns = np.arange(image.shape[-1])
        axis.plot(columns, truth, color="#00E5FF", linewidth=1.2)
        axis.plot(columns, predicted, color="#FF2D95", linewidth=1.0)
        axis.set_title(f"{key[1]} {key[2]} · {group_median:.0f} µm", fontsize=9)
        axis.set_axis_off()
    for axis in axes.ravel()[len(selected):]: axis.set_axis_off()
    fig.text(.5, .01, "reference interface (cyan)    predicted interface (magenta)", ha="center", fontsize=9)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(args.output, dpi=220, bbox_inches="tight", facecolor="white")
    print(args.output)


if __name__ == "__main__":
    main()
